version: '3.8'

services:
  job-order:
    build: .
    container_name: job-order
    restart: unless-stopped
    ports:
      - "1003:1003"
    networks:
      - job-order-client
  
networks:
  job-order-client:
    driver: bridge
