import { ROLES } from "@/constants/roles";

const ADMIN_ACCESS = [ROLES.ADMIN];

const EMPLOYEE_ACCESS = [ROLES.ADMIN, ROLES.EMPLOYEE];

const ACCOUNTING_ACCESS = [ROLES.ADMIN, ROLES.ACCOUNTING];

const AUDIT_ACCESS = [ROLES.ADMIN, ROLES.ACCOUNTING, ROLES.AUDIT];

const REPORTS_ACCESS = [ROLES.ADMIN, ROLES.ACCOUNTING, ROLES.AUDIT];

export {
  ADMIN_ACCESS,
  EMPLOYEE_ACCESS,
  ACCOUNTING_ACCESS,
  AUDIT_ACCESS,
  REPORTS_ACCESS,
};
