services:
  job-order-server:
    build:
      context: ./
      dockerfile: Dockerfile
    image: job-order-server
    container_name: job-order-server
    restart: unless-stopped
    working_dir: /var/www/
    volumes:

      - /home/webserver/systems/Job-Order/client/.env:/var/www/.env
      - ./:/var/www
      - ./docker-compose/nginx/default.conf:/etc/nginx/nginx.conf

    networks:
      - job-order
    environment:
      DB_CONNECTION: mysql
      DB_HOST: 172.17.0.1
      DB_PORT: 3306
      DB_DATABASE: job-order
      DB_USERNAME: smct
      DB_PASSWORD: smct
    # command: php artisan queue:listen --tries=1

  job-order-nginx:
    image: nginx:alpine
    container_name: job-order-nginx
    restart: unless-stopped
    ports:
      - 1004:1004
    volumes:
      - ./docker-compose/nginx/default.conf:/etc/nginx/nginx.conf
      - ./:/var/www

    networks:
      - job-order

  # job-order-reverb:
  #   build:
  #     context: ./
  #     dockerfile: Dockerfile-reverb
  #   ports:
  #   - "8083:8083" # expose Reverb server
  #   environment:
  #   - APP_URL=${APP_URL}
  #   - LARAVEL_REVERB_APP_KEY=${REVERB_APP_KEY}
  #   - LARAVEL_REVERB_APP_SECRET=${REVERB_APP_SECRET}
  #   depends_on:
  #   - job-order-server
  #   restart: unless-stopped
  #   container_name: job-order-reverb

    # networks:
    #   - job-order

networks:
  job-order:
    driver: bridge
